<?php

if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
    'key' => 'oc_clinic_acf_group',
    'title' => 'User Profile',
    'fields' => array(
        array(
            'key' => 'oc_user_staff',
            'label' => 'スタッフ表示設定',
            'name' => 'is_staff',
            'type' => 'true_false',
            'instructions' => 'サイトにスタッフとして表示掲載するか設定',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => 'スタッフとして表示',
            'ui_off_text' => '表示しない',
        ),
        array(
            'key' => 'oc_user_priority',
            'label' => '優先度',
            'name' => 'priority',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                100 => '最優先(100)',
                90 => '90',
                80 => '80',
                70 => '70',
                60 => '60',
                50 => '高(50)',
                40 => '40',
                30 => '平均(30)',
                20 => '20',
                10 => '低(10)',
                20 => '20',
                1 => '1',
                0 => '0',
            ),
            'default_value' => 30,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'oc_user_clinic_title',
            'label' => '院内肩書き',
            'name' => 'oc_user_clinic_title',
            'type' => 'text',
            'instructions' => '院長、歯科医師、歯科衛生士、受付、スタッフなど',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'oc_user_public_title',
            'label' => '一般肩書',
            'name' => 'oc_user_public_title',
            'type' => 'text',
            'instructions' => '「日本矯正歯科学会認定医　歯学博士」「歯科衛生士」「歯科助手」など',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'oc_user_cover_img',
            'label' => 'ユーザーカバー写真',
            'name' => 'oc_user_cover_img',
            'type' => 'image',
            'instructions' => '1500px以上推奨　',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'oc_user_square_img',
            'label' => 'ユーザー正方形写真',
            'name' => 'oc_user_square_img',
            'type' => 'image',
            'instructions' => '1:1の比率、横300px,縦300px以上の大きさ推奨　',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'oc_user_portait_img',
            'label' => 'ユーザー縦長写真',
            'name' => 'oc_user_portait_img',
            'type' => 'image',
            'instructions' => '3:4の比率、横300px,縦400px以上の大きさ推奨　',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'oc_user_wide_img',
            'label' => 'ユーザー横長写真',
            'name' => 'oc_user_wide_img',
            'type' => 'image',
            'instructions' => '4:3の比率、横400px,縦300px以上の大きさ推奨　',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'oc_user_family_name_en',
            'label' => '姓(英語)',
            'name' => 'oc_user_family_name_en',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'oc_user_given_name_en',
            'label' => '名(英語)',
            'name' => 'oc_user_given_name_en',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'oc_user_career',
            'label' => '経歴',
            'name' => 'oc_user_career',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'oc_user_qualification',
            'label' => '所属・資格',
            'name' => 'oc_user_qualification',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'oc_user_scholarly_paper',
            'label' => '論文',
            'name' => 'oc_user_scholarly_paper',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'oc_user_conference',
            'label' => '学会発表・講演',
            'name' => 'oc_user_conference',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'oc_author_field_hobby',
            'label' => '趣味',
            'name' => 'oc_user_hobby',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'user_form',
                'operator' => '==',
                'value' => 'all',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
    'key' => 'group_6263362c95523',
    'title' => '投稿',
    'fields' => array(
        array(
            'key' => 'oc_post_if_show_top_author',
            'label' => 'タイトル下の著者表示',
            'name' => 'oc_post_if_show_top_author',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'oc_post_if_show_bottom_author',
            'label' => '記事下部の著者表示',
            'name' => 'oc_post_if_show_bottom_author',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'default',
            ),
        ),
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ),
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'default',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    ));
endif;
